from typing import Any, Mapping, Optional, Sequence, Union

import setuptools


def setup(
    name: str,
    version: Optional[str] = None,
    description: Optional[str] = None,
    long_description: Optional[str] = None,
    long_description_content_type: Optional[str] = None,
    author: Optional[str] = None,
    author_email: Optional[str] = None,
    maintainer: Optional[str] = None,
    maintainer_email: Optional[str] = None,
    url: Optional[str] = None,
    download_url: Optional[str] = None,
    packages: Optional[Sequence[str]] = None,
    py_modules: Optional[Sequence[str]] = None,
    scripts: Optional[Sequence[str]] = None,
    ext_package: Optional[str] = None,
    ext_modules: Optional[Sequence[setuptools.Extension]] = None,
    classifiers: Optional[Sequence[str]] = None,
    distclass: Optional[setuptools.Distribution] = None,
    script_name: Optional[str] = None,
    script_args: Optional[Sequence[str]] = None,
    options: Optional[Mapping[str]] = None,
    license: Optional[str] = None,
    keywords: Optional[Union[Sequence[str], str]] = None,
    platforms: Optional[Union[Sequence[str], str]] = None,
    cmdclass: Optional[Mapping[str, setuptools.Command]] = None,
    package_dir: Optional[Mapping[str, str]] = None,
    include_package_data: Optional[bool] = None,
    package_data: Optional[Mapping[str, str]] = None,
    zip_safe: Optional[bool] = None,
    install_requires: Optional[Union[Sequence[str], str]] = None,
    entry_points: Optional[Mapping[str, Union[str, Sequence[str]]]] = None,
    extras_require: Optional[Mapping[str, Union[str, Sequence[str]]]] = None,
    python_requires: Optional[str] = None,
    namespace_packages: Optional[Sequence[str]] = None,
    eager_resources: Optional[Sequence[str]] = None,
    project_urls: Optional[Mapping[str, str]] = None,
    **kwargs: Any,
) -> setuptools.Distribution:
