---
name: 🐛 Bug report
description: >-
  Create a report to help us improve when
  something is not working correctly
title: '[BUG] '
labels:
- bug
- Needs Triage

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a bug in setuptools!**


      ⚠
      Verify first that your issue is not
      [already reported on GitHub][issue search] and keep in mind and
      keep in mind that we may have to keep the current behavior because
      [every change breaks someone's workflow][XKCD 1172].
      We try to be mindful about this.

      Also test if the latest release and main branch are affected too.


      If you are seeking community support, please consider
      [starting a discussion][Discussions].


      Thank you for your collaboration!


      [Discussions]: https://github.com/pypa/setuptools/discussions

      [issue search]: https://github.com/pypa/setuptools/search?q=is%3Aissue&type=issues

      [XKCD 1172]: https://xkcd.com/1172/

- type: markdown
  attributes:
    value: >-
      **Environment**
- type: input
  attributes:
    label: setuptools version
    placeholder: For example, setuptools==69.1.0
    description: >-
      Please also test with the **latest version** of `setuptools`.

      Typically, this involves modifying `requires` in `[build-system]` of
      [`pyproject.toml`](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use),
      not just updating `setuptools` using `pip`.
  validations:
    required: true
- type: input
  attributes:
    label: Python version
    placeholder: For example, Python 3.10
    description: >-
      Please ensure you are using a [supported version of Python](https://devguide.python.org/versions/#supported-versions).

      Setuptools does not support versions that have reached [`end-of-life`](https://devguide.python.org/versions/#unsupported-versions).

      Support for versions of Python under development (i.e. without a stable release) is experimental.
  validations:
    required: true
- type: input
  attributes:
    label: OS
    placeholder: For example, Gentoo Linux, RHEL 8, Arch Linux, macOS etc.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional environment information
    description: >-
      Feel free to add more information about your environment here.
    placeholder: >-
      This is only happening when I run setuptools on my fridge's patched firmware 🤯

- type: textarea
  attributes:
    label: Description
    description: >-
      A clear and concise description of what the bug is.
    placeholder: >-
      I tried doing X and I expected it to result in Y because the docs
      mentioned Z but what happened next what totally unexpected!
      And here's why...
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      A clear and concise description of what you expected to happen.
    placeholder: >-
      I tried doing X and I expected it to result in Y. I'm confused...
  validations:
    required: true

- type: textarea
  attributes:
    label: How to Reproduce
    description: >-
      Describe the steps to reproduce this bug.

      Please try to create a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example),
      and avoid things like "see the steps in the CI logs".
    placeholder: |
      1. Clone a simplified example: `git clone ...`
      2. Create a virtual environment for isolation with `...`
      2. Build the project with setuptools via '...'
      2. Then run '...'
      3. An error occurs.
  validations:
    required: true

- type: textarea
  attributes:
    label: Output
    description: >-
      Paste the output of the steps above, including the commands
      themselves and setuptools' output/traceback etc.
    value: |
      ```console

      ```
  validations:
    required: true

...
