import os
import shutil
from pathlib import Path

_vendored_distutils_path = Path(__file__).parent.parent / "setuptools" / "_distutils"
_distutils_stubs_path = Path(__file__).parent.parent / "typings" / "distutils-stubs"

DONT_TOUCH_COMMENT = "# DO NOT MODIFY ! This file was automatically generated by tools/update_distutils_stubs.py\n"


def main():
    if _distutils_stubs_path.exists():
        shutil.rmtree(_distutils_stubs_path)
    _distutils_stubs_path.mkdir(parents=True)
    (_distutils_stubs_path / "ruff.toml").write_text(
        f'{DONT_TOUCH_COMMENT}[lint]\nignore = ["F403"]'
    )
    for path in _vendored_distutils_path.rglob("*.py"):
        relative_path = path.relative_to(_vendored_distutils_path)
        if relative_path.parts[0] == "tests":
            continue
        stub_path = (_distutils_stubs_path / relative_path).with_suffix(".pyi")
        stub_path.parent.mkdir(exist_ok=True)
        module = (
            "setuptools._distutils."
            + str(relative_path.with_suffix("")).replace(os.sep, ".")
        ).removesuffix(".__init__")
        stub_path.write_text(f"{DONT_TOUCH_COMMENT}from {module} import *\n")


if __name__ == "__main__":
    main()
